### ISSUE TITLE
Plugin name/version displays as "Template 0.0.0.0" in Plugins menu

### ISSUE THREAD

**Issue by Gunther0042** [arition/jellyfin-plugin-ignore#2]
Amazing plugin! The core functionality is working perfectly for me.

However, in the plugins menu the name and version displays as "Template 0.0.0.0". This is a cosmetic bug, but would still be nice to fix. I imagine it is just some variables from the template used for this plugin that were never changed.

I am running Jellyfin on Ubuntu and I used the pre-built binary for the plugin that was in the releases section.

**Comment by arition** [comment]
Fixed in latest release
